language: node_js

node_js:
  - "node"
env:
  global: CC_TEST_REPORTER_ID=f05e52daa7be717108dbd8228ce88f00a8bb39946b312c6dd07641abac0aa8e8
install:
  - npm install
cache:
  directories:
    - "node_modules"
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_success:
    - npm run coverage
    - npm install codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
    